export const data = [
	{
		id: 1,
		day: 1,
		name: "یک",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 2,
		day: 2,
		name: "دو",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 3,
		day: 3,
		name: "سه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 4,
		day: 4,
		name: "چهار",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 5,
		day: 5,
		name: "پنج",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 6,
		day: 6,
		name: "شش",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 7,
		day: 7,
		name: "هفت",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 8,
		day: 8,
		name: "هشت",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس وفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
	{
		id: 9,
		day: 9,
		name: "نه",
		content1name: "1عکس وفیلم",
		content1des: "توضیحات لورم ثضصثضصثضصثضصثضصثضصثضصثضصثایپسوم توضیحات کانتنت ",
		content1bgColor: "red",
		content2name: "2عکس ضصثضصثضصثضصضصثضصثضصثضصثثوفیلم",
		content2des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content2bgColor: "blue",
		content3name: "3عکس وفیلم",
		content3des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content3bgColor: "yellow",
		content4name: "4عکس وفیلم",
		content4des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content4bgColor: "green",
		content5name: "5عکس وفیلم",
		content5des: "توضیحات لورم ایپسوم توضیحات کانتنت ",
		content5bgColor: "pink",
	},
];

// const newData = data.map((item) => {
// 	var words = item.name.split(" ");
// 	var maxWords = 6; // Set the maximum number of words to display

// 	if (item.name.length > maxWords) {
// 		var truncatedText = words.slice(0, maxWords).join(" ") + "...";
// 		item.name = truncatedText;
// 	}
// });

const maxLength = 11;

data.map((item) => {
	if (item.content2name.length > maxLength) {
		item.content2name = item.content2name.slice(0, maxLength) + "...";
	}
});

console.log(data);
